const DEFAULT_API_VERSION = process.env.NEXT_PUBLIC_DEFAULT_API_VERSION;

const API_BASE_PATH = process.env.NEXT_PUBLIC_API_BASE_PATH;

const BACKEND_BASE_URL = "";

export const API_BASE_URL = `${BACKEND_BASE_URL}${API_BASE_PATH}${DEFAULT_API_VERSION}`;
