import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { WalletContextProvider } from "@/contexts/wallet.context";
import CheckSetupedWallet from "@/CheckSetupedWallet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletContextProvider>
          <CheckSetupedWallet />
          <Toaster position="top-center" reverseOrder={false} />
          {children}
        </WalletContextProvider>
      </body>
    </html>
  );
}
